### ISSUE TITLE
HTML colors are not colorblind-friendly

### ISSUE THREAD

**Issue by palazzol** [mtfurlan/buddys-menu-scraping#1]
Why did you choose gray and slightly bluer gray? :)

**Comment by mtfurlan** [comment]
Ah, I see you don't get along the bootstrap defaults for `table-danger` and `table-success`.

What off this list should we use: https://getbootstrap.com/docs/4.0/content/tables/#contextual-classes
Could do arbitrary colours, but the rows alternating brightness would be harder.

**Comment by mtfurlan** [comment]
Actually, icons are probably a better solution.

**Comment by mtfurlan** [comment]
Check it out now, is it readable to you: https://buddys.technicallycompetent.com/
